package io.github.anistor.jackpot.controller;

import java.math.BigDecimal;
import java.util.Optional;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

// TODO We could also consider letting the client generate the unique bet id and thus help the client also rely on this for idempotency
//  (if the client has a retry mechanism that could lead to double posting).

/**
 * Request for placing a bet. A bet id is generated by the service after accepting the request and then it is returned to the caller for future reference.
 */
public record PlaceBetRequest(
        Optional<String> betId, // optional, experimental, as per todo
        @NotBlank String userId,
        @NotBlank String jackpotId,
        @NotNull @Positive BigDecimal amount) {
}
